# Generated by Django 5.0.4 on 2024-04-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(default='blog_images/default.png', upload_to='blog_images'),
        ),
    ]
