# Generated by Django 5.0.4 on 2024-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_blog_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(upload_to='blog_images'),
        ),
    ]
