# Generated by Django 5.0.4 on 2024-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default=0, upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
