# Generated by Django 5.0.4 on 2024-04-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
    ]
