# Generated by Django 5.0.4 on 2024-04-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_images/user.png', null=True, upload_to='profile_images', verbose_name='Profile Pic'),
        ),
    ]
